### ISSUE TITLE
Go error during failover: slice bounds out of range

### ISSUE THREAD

**Issue by banpei-dbart** [mariadb-corporation/replication-manager#11]
I'm testing MRM at the moment and I'm getting the following error when failing over manually:

> /usr/local/bin/replication-manager` --user=root:pass --rpluser=repl:replpass --hosts=10.10.18.11:3306,10.10.18.12:3306,10.10.18.13:3306 --failover=force --interactive=false --logfile=/var/log/failover.log
> 2016/03/16 11:02:39 INFO : Server 10.10.18.11:3306 is dead.
> panic: runtime error: slice bounds out of range
> 
> goroutine 1 [running]:
> main.(*TermLog).Add(0x877670, 0xc20802c300, 0x33)
> 	/home/vagrant/replication-manager/termlog.go:19 +0x37b
> main.logprint(0xc208075900, 0x1, 0x1)
> 	/home/vagrant/replication-manager/display.go:99 +0x502
> main.masterFailover(0x7fff109ac801)
> 	/home/vagrant/replication-manager/failover.go:12 +0x10f
> main.main()
> 	/home/vagrant/replication-manager/repmgr.go:285 +0x210c
> 
> goroutine 5 [syscall]:
> os/signal.loop()
> 	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
> created by os/signal.init·1
> 	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35
> 
> goroutine 6 [chan receive]:
> database/sql.(*DB).connectionOpener(0xc208034140)
> 	/usr/lib/golang/src/database/sql/sql.go:589 +0x4c
> created by database/sql.Open
> 	/usr/lib/golang/src/database/sql/sql.go:452 +0x31c
> 
> goroutine 8 [runnable]:
> database/sql.(*DB).connectionOpener(0xc2080341e0)
> 	/usr/lib/golang/src/database/sql/sql.go:589 +0x4c
> created by database/sql.Open
> 	/usr/lib/golang/src/database/sql/sql.go:452 +0x31c
> 
> goroutine 9 [runnable]:
> database/sql.(*DB).connectionOpener(0xc208034000)
> 	/usr/lib/golang/src/database/sql/sql.go:589 +0x4c
> created by database/sql.Open
> 	/usr/lib/golang/src/database/sql/sql.go:452 +0x31c

I tried to resolve it but Go isn't one of my used languages. I saw you didn't touch the termlog.go file in the past 5 months, but did change the behavior of logging in display.go. It seems to be a problem with somewhere exceeding the length of the TermLog.

I also had a different issue with the MaxScale/MRM failover: MaxScale only seems to send the list of nodes that are up in the $NODESLIST variable. This used to be the complete list of nodes and I don't know if this behavior changed in 1.3.0?

**Comment by tanji** [comment]
Hi,

Yes, I can see the problem, although I am not sure why it occurs - I have never encountered this issue myself. I will release a fix.

For MaxScale, yes, it is indeed a problem - I will talk to the MaxScale team about this.

Thanks for reporting!

**Comment by banpei-dbart** [comment]
Thanks!
For now I prepended the hosts with the $initiator and this should work in theory.

**Comment by banpei-dbart** [comment]
Just pulled the latest version, compiled it and it works now:
sudo /usr/local/bin/replication-manager --user=root:toor --rpluser=repl:repl --hosts=10.10.18.11:3306,10.10.18.12:3306,10.10.18.13:3306 --failover=force --interactive=false --logfile=/var/log/failover.log
2016/03/16 14:43:05 INFO : Server 10.10.18.11:3306 is dead.
2016/03/16 14:43:05 INFO : Starting master switch
2016/03/16 14:43:05 INFO : Electing a new master

Thanks! :+1:

**Comment by himbeere** [comment]
Ran into the same problem. Can we have a new release for this @tanji?

thanks and cheers

**Comment by himbeere** [comment]
@tanji just saw there is already one. You are too fast for me. :-)

**Comment by tanji** [comment]
@banpei-dbart I heard from the MaxScale Team that this change of behavior was wanted, so I have to update my failover instructions as well, it seems... sorry for that.

**Comment by banpei-dbart** [comment]
No problem. Thanks for asking them! :)
