### ISSUE TITLE
[0.6.2]Failover and switchover are failed : invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jerrylin0** [mariadb-corporation/replication-manager#13]
Hi ,
The failover and switchover functions are failed .
The failover error message as below :
2016/03/17 12:21:57 INFO : Server mdb1:9801 is dead.
2016/03/17 12:21:57 INFO : Starting master switch
2016/03/17 12:21:57 INFO : Electing a new master
2016/03/17 12:21:57 INFO : Slave mdb2:9801 [0] has been elected as a new master
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40cdc8]

goroutine 1 [running]:
panic(0x702de0, 0xc82000e0f0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*ServerMonitor).delete(0xc820070640, 0x8f41e0)
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/monitor.go:259 +0x208
main.masterFailover(0x7fff32300701)
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/failover.go:44 +0x9d1
main.main()
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/repmgr.go:286 +0x218d

The switchover error message as below :
2016-03-17 11:54:32 Monitor started in switchover mode
2016-03-17 11:54:52 INFO : Slave mdb2:9801 [0] has been elected as a new master
 2016-03-17 11:54:52 DEBUG: Election rig: mdb2:9801 elected as preferred master
 2016-03-17 11:54:52 DEBUG: Checking eligibility of slave server mdb2:9801
 2016-03-17 11:54:52 DEBUG: Processing 2 candidates
 2016-03-17 11:54:52 INFO : Electing a new master
 2016-03-17 11:54:52 INFO : Checking long running updates on master
 2016-03-17 11:54:52 INFO : Flushing tables on mdb1:9801 (master)
 2016-03-17 11:54:52 INFO : Starting master switch
 2016-03-17 11:54:32 Monitor started in switchover modepanic: runtime error: invalid memory address or nil pointer dereference
                         [signal 0xb code=0x1 addr=0x0 pc=0x40cdc8]

                                                                   goroutine 1 [running]:
                                                                                         panic(0x702de0, 0xc82000e100)
                        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
                                                                   main.(*ServerMonitor).delete(0xc820072640, 0x8f41e0)
                        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/monitor.go:259 +0x208
                 main.masterFailover(0xc8202b7e00)
                                                        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/failover.go:44 +0x9d1
                                                 main.main()
                                                                /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/repmgr.go:313 +0x2a5c

**Comment by tanji** [comment]
Hi @jerrylin0 

Which command have you been using?

**Comment by jerrylin0** [comment]
Hi ,
./replication-manager --hosts=mdb1:9801,mdb2:9801,mdb3:9801 --user=dba:dba --rpluser=rep:rep --prefmaster=mdb2:9801 --failover=force

and

./replication-manager --hosts=mdb1:9801,mdb2:9801,mdb3:9801 --user=dba:dba --rpluser=rep:rep --prefmaster=mdb2:9801 --switchover=keep

**Comment by tanji** [comment]
Please try new version 0.6.3

**Comment by jerrylin0** [comment]
Hi Guillaume,

Thanks for your hard work .
I had test the failover and switchover functions ,now they can work without any error log .

But in failover.sh script ,it can not receive the $nodelist  variable.
Which one is wrong cause,Maxsacle , MRM or failover script?

**Comment by tanji** [comment]
Hi Jerry,

thanks! 

MaxScale have changed the way they handle this in 1.3.0, so you should not use the failover script anymore. Instead you should use this:

```
script=/usr/local/bin/replication-manager --user root:admin --rpluser repluser:replpass --hosts $INITIATOR,$NODELIST --failover=force --interactive=false
```

Let me know if that works for you.

**Comment by jerrylin0** [comment]
Hi Guillaume,

This script command also can not work .
I had test to print the two variables of  $INITIATOR and $NODELIST,I got  the null both the two variables.

--Jerry
