### ISSUE TITLE
replication-manager 0.6 question?

### ISSUE THREAD

**Issue by sysdljr** [mariadb-corporation/replication-manager#14]
replication-manager --version
MariaDB Replication Manager version 0.6.3

master: 172.28.14.118  mariadb 10.0.23
slave:   172.28.14.114   mariadb 10.0.23

Both master and slave service normal,  read and write not problem too, But execute replication-manager at below:
replication-manager --user=root:123456 --rpluser=root:123456 --hosts=172.28.14.118:3306 --failover=force --socket=/home/mtest1/data/mysql.sock
2016/03/18 11:21:06 **ERROR: Could not autodetect a failed master!**

replication-manager --user=root:123456 --rpluser=root:123456 --hosts=172.28.14.118:3306,172.28.14.114:3306 --failover=force --socket=/home/mtest1/data/mysql.sock
2016/03/18 11:21:28 **ERROR: Multi-master topologies are not yet supported.
**
Is  our's configure or grammar have problem ?

**Comment by sysdljr** [comment]
Sorry. Just found two machines config dual master , Besides 172.28.14.118 is master,  it is too 172.28.14.114 slave.
replication-manager consider to add Judgment condition for dual master in the future. Thanks

**Comment by tanji** [comment]
OK. Closing this for now
