### ISSUE TITLE
Both failover and switchover are failed

### ISSUE THREAD

**Issue by jerrylin0** [mariadb-corporation/replication-manager#15]
Hi ,

A few days ago ,I test the MRM-0.6.3 with failover and switchover .
When I want to do failover via Maxscale ,the mrm show message "could not autodetect a failed master" , I'm sure the master is down and the slaves are live .

When I want to do switchover ,the mrm show message "no suitable candidates found" ,I have use --prefmaster option to choice the new master .

I want to reproduce the two issues ,but I can't reproduce they again .

Could you tell me what's problem could cause the two issue ?
Thank you.

**Comment by tanji** [comment]
Hi!

Can you copy the maxscale configuration you use for this failover setup, especially the script= line?
Do you have a mrm.log file? you can activate it with --logfile=/var/log/mrm.log, for example.

**Comment by jerrylin0** [comment]
Hi ,
Today I re-configure my failover.sh script and I can do failover and switchover well .
Thanks for your help.
