### ISSUE TITLE
Replication manager does not support named connections

### ISSUE THREAD

**Issue by hugochinchilla** [mariadb-corporation/replication-manager#16]
I cannot use this tool because of `SHOW SLAVE STATUS` returns no information on my slave as the replication is configured using a named connection and instead it should do `SHOW SLAVE 'foobar' STATUS`.

Instead of suggesting to add a parameter to set the connection name I would suggest to add an argument to allow setting arbitrary variables onto the session like I can do with pt-table-checksum, then I could do `--set-vars default_master_connection=foobar` and the tool would be able to work with my setup.

Before you tell me than multisource replication is not  supported with this tool I would like to clarify my setup:

I have 5 mariadb servers,  B replicates from A, D replicates from C, E replicates from A and C, I would never include D in a switchover event, it is a backup server we use only for taking snapshots and data indexing, a switchover event would be always between A and B or between C and D, I had to rename the replication in thoose servers to match the names configured on D, otherwise I could not use pt-table-checksum to monitor the data on my servers.

**Comment by tanji** [comment]
Hello,

sure! this sounds like a reasonable request... However, regarding the default master connection, I think it is worth having a parameter just for it, because this is something we might want to use, especially in 0.7 where configuration files are supported.

**Comment by hugochinchilla** [comment]
Ok, I have a coworker (@servomac) working on a PR, for now we will drop de idea of --set-vars and work on a flag to set the connection name, in a few hours it might be ready .

**Comment by servomac** [comment]
We have a first functional implementation using the --master-connection flag, relying on a fork of dbhelper (that adds some functions for named connections).

https://github.com/Habitissimo/mariadb-tools/commit/1367368c8d03a610157ac01876874d9dbf665dd5
https://github.com/Habitissimo/replication-manager

**Comment by tanji** [comment]
I'll probably have to implement the functionality in a different manner in 0.7, because your patch changes too many things. Until then I will leave this issue open.

**Comment by hugochinchilla** [comment]
We tried to touch the bare minimum to make it work, how would you sugest to make the changes? We would prefer to submit a PR than you can accept so we can forget about maintaining a fork.

**Comment by tanji** [comment]
I have modified the code extensively in 0.7, so there's a lot of stuff which is gone and replaced etc.
I'd rather make the changes based on your fork so you can make it work with very minimal changes. Trust me :)

**Comment by hugochinchilla** [comment]
Ok, we didn't notice the 0.7 branch, we can make the PR against that branch after a review if you want.

**Comment by tanji** [comment]
Fixed in https://github.com/mariadb-corporation/replication-manager/commit/7d97353388bdd7c17594421f81045794581def23

**Comment by hugochinchilla** [comment]
Thank you very much @tanji, that was quick ;)
