### ISSUE TITLE
Keep state of the last failover in non-interactive mode

### ISSUE THREAD

**Issue by banpei-dbart** [mariadb-corporation/replication-manager#17]
If MRM is used in interactive mode there is a limit on the number of failovers that it does and this number is obviously kept somewhere inside the application as a state. However when using MRM with MaxScale it is used as a single failover and exits after performing the task and thus it doesn't keep state. This could lead to flapping issues.

If you would be able to keep the state of the previous failover(s) and add a timestamp of the last failover there you could add this protection also with the single execution.

**Comment by tanji** [comment]
Good point. I'll implement something!
