### ISSUE TITLE
Please implement slave catchup timeout instead of gtidcheck

### ISSUE THREAD

**Issue by michaeldg** [mariadb-corporation/replication-manager#24]
Currently the documentation (in --help) of the --gtidcheck feature is unclear. It would be more useful if there was a timeout instead of a switch for this.

The timeout should determine how long mrm waits until it considers the slave to be too far out of sync to do the switchover. I think a default of 30 seconds is good in most cases.

**Comment by tanji** [comment]
Doesn't --maxdelay <seconds> satisfy this requirement already?
