### ISSUE TITLE
Cannot connect to node error: Pleasse add hostname

### ISSUE THREAD

**Issue by michaeldg** [mariadb-corporation/replication-manager#27]
I was unable to connect to db4 (mysql schema is not replicated and I forgot to add credentials there). It would save me a fair bit of time if the error said the issue was at db4.

mariadb@maxscale01:~$ ./go/bin/replication-manager --hosts=db1,db2,db3,db4 --user=replication_manager:..... --rpluser=slave_user --interactive --switchover=keep
2016/06/10 13:54:51 ERROR: Database access denied: Error 1045: Access denied for user 'replication_manager'@'172.27.4.103' (using password: YES)

**Comment by whatot** [comment]
In the code , `stmt := "SELECT Select_priv, Process_priv, Super_priv, Repl_slave_priv, Repl_client_priv FROM mysql.user WHERE user = ? AND host = ?"` is the key code.
So the wildcard doesn't work neither.
But there is no simple way to deal with the user and privilege problems in current codebase.

**Comment by tanji** [comment]
@whatot you are right. thanks for spotting this one.

**Comment by tanji** [comment]
Actually the wildcard is correctly tested in dbhelper. However the credentials are not tested in repmgr.
