### ISSUE TITLE
Panic: runtime error: index out of range

### ISSUE THREAD

**Issue by swar0g** [mariadb-corporation/replication-manager#3]
Just got the latest binaries and tried to setup failover with simple master-slave replication. Somehow like this:

mariadb-repmgr -user user:user -rpluser repl:repl -hosts 10.0.0.2:3306,10.0.0.3:3306 -failover=force

Master went down and I got:

panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
        /home/tanj/Dev/go/src/github.com/tanji/mariadb-tools/mariadb-repmgr/repmgr.go:187 +0x2c5a

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208046140)
        /usr/lib/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:452 +0x31c

goroutine 7 [runnable]:
database/sql.(*DB).connectionOpener(0xc2080461e0)
        /usr/lib/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:452 +0x31c

Any clue how to solve?

**Comment by tanji** [comment]
I would say that was due to authentication errors which were not handled correctly, probably you were using the wrong user/pass combination and that led to a panic.
I've added some code to catch those errors in the latest release. Let me know if it works.

**Comment by swar0g** [comment]
I confirm, the problem is solved. Thank you. Now I get:

2015/11/30 10:18:22 INFO : Server 10.0.0.2:3306 is dead.
2015/11/30 10:18:22 ERROR: No slaves were detected.

No more panic.
