### ISSUE TITLE
replication-manager doesn't work with Amazon RDS, maxscale 

### ISSUE THREAD

**Issue by psachin-ic** [mariadb-corporation/replication-manager#32]
I tried to use replication-manager on my two Amazon RDS host but it errored out with Super privilege.
Amazon RDS doesn't give SUPER privilege to RDS users.

/usr/local/bin/replication-manager --user=XXX:XXX123 --rpluser=XXXX:XXXX --hosts=TEST1.rds.amazonaws.com,TEST2.rds.amazonaws.com --failover=monitor
2016/06/13 10:50:11 ERROR: User must have SUPER privilege

Do we have any ways to proceed with replication manager without super privileges. I have given my user all privileges but not super.

**Comment by tanji** [comment]
You cannot control the replication in RDS. Please see https://aws.amazon.com/rds/faqs/
If you want to control your own replication, please use AWS EC2 MariaDB images.
