### ISSUE TITLE
ERROR: No slaves were detected

### ISSUE THREAD

**Issue by swar0g** [mariadb-corporation/replication-manager#4]
Sorry to bother you again, but I still have problem with my configuration. Structure looks like following:

3 servers: 1 maxscale (10.0.0.1), 1 mariadb master(10.0.0.2), 1 mariadb slave(10.0.0.3).

Simple test to exchange master-slave fails with following output:

__replication-manager -user user:user -rpluser replica:repl1ca -hosts 10.0.0.2:3306,10.0.0.3:3306 -failover=force -verbose__

>2015/11/30 10:59:49 DEBUG: Creating new server: 10.0.0.2:3306
>2015/11/30 10:59:49 DEBUG: Checking if server 10.0.0.2:3306 is slave
>2015/11/30 10:59:49 DEBUG: Server 10.0.0.2:3306 is not a slave. Setting aside
>2015/11/30 10:59:49 DEBUG: Creating new server: 10.0.0.3:3306
>2015/11/30 10:59:49 DEBUG: Checking if server 10.0.0.3:3306 is slave
>2015/11/30 10:59:49 DEBUG: Server 10.0.0.3:3306 is not a slave. Setting aside
>2015/11/30 10:59:49 ERROR: No slaves were detected.

Was looking for the error massage in sources and found following condition:

>if servers[k].UsingGtid != "" 

But on slave Using_Gtid value is definitely not empty:

>Using_Gtid: Current_Pos
>Gtid_IO_Pos: 0-1-12542

So, I am just curious what to check next.

**Comment by tanji** [comment]
I think your user (user:user) might lack privileges to read the slave status on the slave.

I have a Work Item which is to check that the user account has correct permissions to operate replication-manager. Can you please try the following from the box where you execute repmgr?

`mysql -u user -p -h 10.0.0.3 -e "SHOW SLAVE STATUS"`

Another unrelated thing, but if you want to exchange master and slave, don't use `-failover=force`. this assumes that the master is down.
Use `-switchover=keep -interactive=false` instead.

Thanks!

**Comment by swar0g** [comment]
That was the first thing I thought of, but it is not. User has all the privileges and the right output is shown. I have added some breakpoint into code and was able to catch the following error:

missing destination name Replicate_Do_Domain_Ids

after dbhelper.GetSlaveStatus(sm.Conn). 

Relative line in slave status looks like:

Using_Gtid: Current_Pos
Gtid_IO_Pos: 1-1-1
Replicate_Do_Domain_Ids:
Replicate_Ignore_Domain_Ids:

**Comment by swar0g** [comment]
Forgot to mention, it could be important: I am using the following version:

mysql  Ver 15.1 Distrib 10.1.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by tanji** [comment]
Ah, that explains all. It is not 10.1 compatibility-tested yet, however the fix should be very easy (Indeed there are a few changes in SHOW SLAVE STATUS). I'll commit the fix later today if I'm not too busy with other things. Thanks for reporting that!

**Comment by tanji** [comment]
Hi!

Please update the mariadb-tools external dependency:

`go install github.com/tanji/mariadb-tools`

And rebuild replication-manager.
You shouldn't get this error anymore.

**Comment by swar0g** [comment]
I confirm, the issue is solved. Thank you very much. But, unfortunatelly, I sitll have problems running replication-manager, at the moment output looks like following:

**replication-manager  -user user:user -rpluser replica:replica -hosts db1,db2 -switchover=keep -interactive=false -verbose**

> 2015/12/09 10:34:36 DEBUG: Creating new server: db1
> 2015/12/09 10:34:36 DEBUG: Checking if server db1 is slave
> 2015/12/09 10:34:36 DEBUG: Server db1 is not a slave. Setting aside
> 2015/12/09 10:34:36 DEBUG: Creating new server: db2
> 2015/12/09 10:34:36 DEBUG: Checking if server db2 is slave
> 2015/12/09 10:34:36 DEBUG: Server db2 is configured as a slave
> 2015/12/09 10:34:36 ERROR: Could not autodetect a master!

and in failover mode (with master db1 stopped)

**replication-manager  -user user:user -rpluser replica:replica -hosts db1,db2 -failover=force  -verbose**

> 2015/12/09 10:51:39 DEBUG: Creating new server: db1
> 2015/12/09 10:51:39 INFO : Server db1 is dead.
> 2015/12/09 10:51:39 DEBUG: Creating new server: db2
> 2015/12/09 10:51:39 DEBUG: Checking if server db2 is slave
> 2015/12/09 10:51:39 DEBUG: Server db2 is configured as a slave
> 2015/12/09 10:51:39 DEBUG: Server db1 was autodetected as a master
> 2015/12/09 10:51:39 ERROR: Could not autodetect a failed master!

**Comment by tanji** [comment]
is db1 supposed to be down when you initiate failover? I see that detected:
2015/12/09 10:51:39 INFO : Server db1 is dead.

**Comment by swar0g** [comment]
Yes, it supposed to be down. I thought it is the main idea behind failover: master goes down, one of the slaves becomes master role, and switchover is just degradation of active master to slave, isn't it?

**Comment by tanji** [comment]
Right, just wanted to confirm. I am testing in a lab with MariaDB 10.1 right now, I'll keep you posted.

**Comment by swar0g** [comment]
Thanks. I was able to fix my pb with following changes:

>// Final check if master has been found
>if master == nil {
>if(*switchover != "" || *failover == "monitor") {
>log.Fatalln("ERROR: Could not autodetect a master!")
>} else {
>log.Fatalln("ERROR: Could not autodetect a failed master!")
>}
>}

**Comment by tanji** [comment]
Yes, you are right, the test was wrong. I'll fix this in next release. Thanks!

**Comment by swar0g** [comment]
Thank you . The issue is then closed.

**Comment by tanji** [comment]
Fixed in 36cb7fd08c45c0b8c2e1a2b589c4175ac2cde7c1, thanks for reporting!
