### ISSUE TITLE
Could not autodetect a failed master

### ISSUE THREAD

**Issue by jerrylin0** [mariadb-corporation/replication-manager#5]
Hi ,
When I use command as below ,I got an error message : "Could not autodetect a failed master!"
./mariadb-repmgr -user dba:dba -rpluser rep:rep -hosts db1:3307,db2:3307,db3:3307 -prefmaster=db2:3307 -failover=force
or
./mariadb-repmgr -user dba:dba -rpluser rep:rep -hosts db1:3307,db2:3307,db3:3307 -prefmaster=db2:3307 -switchover=keep

The first command I can executing on 0.4.1 version but the error will occur on 0.5.1 version.

**Comment by tanji** [comment]
It seems similar to #4. Can you build the latest version and try again?

**Comment by tanji** [comment]
Fixed in 0.5.2.
