### ISSUE TITLE
The switchover is not work .

### ISSUE THREAD

**Issue by jerrylin0** [mariadb-corporation/replication-manager#8]
Hi ,
I am testing the MRM 0.52 version.
When I want to do switchover in my lab ,I got an error mesage : "ERROR: Could not autodetect a master!"
My mrm command is "/mariadb/software/mrm/mariadb-repmgr -hosts=mdb1:3306,mdb2:3306,mdb3:3306 -user=admin:admin -rpluser=rep:rep -prefmaster=mdb2:3306 -switchover=keep"

Does my mrm command is wrong ?
If I want to switchover ,how should I use the mrm options ?

**Comment by tanji** [comment]
Hi Jerrylin,

your command is right, maybe it is a problem with the autodetection.

can you add -verbose to the command to generate a log and paste it here?

**Comment by jerrylin0** [comment]
Hi ,
The detailed log as below:
/mariadb/software/mrm/mariadb-repmgr -hosts=mdb1:3306,mdb2:3306,mdb3:3306 -user=admin:admin -rpluser=rep:rep -prefmaster=mdb2:3306 -switchover=keep -verbose
2016/03/09 09:45:33 DEBUG: Creating new server: mdb1:3306
2016/03/09 09:45:33 DEBUG: Checking if server mdb1:3306 is slave
2016/03/09 09:45:33 DEBUG: Server mdb1:3306 is configured as a slave
2016/03/09 09:45:33 DEBUG: Creating new server: mdb2:3306
2016/03/09 09:45:33 DEBUG: Checking if server mdb2:3306 is slave
2016/03/09 09:45:33 DEBUG: Server mdb2:3306 is configured as a slave
2016/03/09 09:45:33 DEBUG: Creating new server: mdb3:3306
2016/03/09 09:45:33 DEBUG: Checking if server mdb3:3306 is slave
2016/03/09 09:45:33 DEBUG: Server mdb3:3306 is configured as a slave
2016/03/09 09:45:33 ERROR: Could not autodetect a master!

But I am sure the mdb1 is master not slave .

In MaxScale ,the "list servers" show the mdb1 is master :
MaxScale> list servers
Servers.
-------------------+-----------------+-------+-------------+--------------------
Server             | Address         | Port  | Connections | Status
-------------------+-----------------+-------+-------------+--------------------
server1            | mdb1            |  3306 |           0 | Master, Running
server2            | mdb2            |  3306 |           0 | Slave, Running
server3            | mdb3            |  3306 |           0 | Slave, Running
-------------------+-----------------+-------+-------------+--------------------

**Comment by tanji** [comment]
Hi Jerry,

I think this happens because master1 is detected as a slave:

`2016/03/09 09:45:33 DEBUG: Server mdb1:3306 is configured as a slave`

Please reset the slave configuration on mdb1 by using `RESET SLAVE ALL` statement.

**Comment by jerrylin0** [comment]
Hi ,
Thank you.
The switchover function is work .
