### ISSUE TITLE
version 0.60 ERROR: Could not autodetect a master!

### ISSUE THREAD

**Issue by himbeere** [mariadb-corporation/replication-manager#9]
Hello.

I have a problem with the brandnew 0.60 version. Here is what i try:

```
/usr/local/bin/replication-manager --version --hosts=10.4.129.11,10.4.129.12 --user=replmgr:pass --rpluser=repl:pass --failover=monitor
```

That gives:
```
MariaDB Replication Manager version 0.6.0-9450672
2016/03/11 21:02:21 ERROR: Could not autodetect a master!
```

With 0.52 this works just fine. Maxscale looks good too.

```
maxscale root # maxadmin -pmariadb "show servers"
Server 0x7f8be0cae3a0 (server1)
        Server:                              10.4.129.11
        Status:                              Master, Running
        Protocol:                    MySQLBackend
        Port:                                3306
        Server Version:                 10.0.23-MariaDB-log
        Node Id:                     4134630
        Master Id:                   -1
        Slave Ids:                   4134631
        Repl Depth:                  0
        Number of connections:               28
        Current no. of conns:                0
        Current no. of operations:   0
Server 0x7f8be0cae2c0 (server2)
        Server:                              10.4.129.12
        Status:                              Slave, Running
        Protocol:                    MySQLBackend
        Port:                                3306
        Server Version:                 10.0.23-MariaDB-log
        Node Id:                     4134631
        Master Id:                   4134630
        Slave Ids:                   
        Repl Depth:                  1
        Number of connections:               28
        Current no. of conns:                0
        Current no. of operations:   0
```

Any hints?

thanks and cheers
t.

**Comment by himbeere** [comment]
Wow. Just noted that the above command works if i append a "--verbose". That's really strange. If i can be of any help debugging this please just ask. Will test more now.

cheers
t.

**Comment by himbeere** [comment]
Hello.

Is it possible i need 3 servers for using replication-manager? With a regular master / slave setup i can't switch.

```
maxscale / # /usr/local/bin/replication-manager --user=replmgr:pass --rpluser=repl:pass --hosts=10.4.129.12,10.4.129.11 --failover=force --verbose
2016/03/12 14:59:38 DEBUG: Creating new server: 10.4.129.12
2016/03/12 14:59:38 DEBUG: Checking if server 10.4.129.12 is slave
2016/03/12 14:59:38 DEBUG: Server 10.4.129.12 is configured as a slave
2016/03/12 14:59:38 DEBUG: Creating new server: 10.4.129.11
2016/03/12 14:59:38 DEBUG: Checking if server 10.4.129.11 is slave
2016/03/12 14:59:38 DEBUG: Server 10.4.129.11 is not a slave. Setting aside
2016/03/12 14:59:38 ERROR: Could not autodetect a failed master!
maxscale / # 
```

**Comment by jerrylin0** [comment]
Hi ,

Maybe you can use prefmaster option to choice a master.

**Comment by himbeere** [comment]
Hi Jerrylin0.

Setting prefmaster does not change things.

Really strange thing is with the --verbose option it works.

```
maxscale / # /usr/local/bin/replication-manager --user=replmgr:pass --rpluser=repl:pass --hosts=10.4.129.11,10.4.129.12 --switchover=keep --logfile=/var/log/mrm.log --verbose --version
MariaDB Replication Manager version 0.6.0-9450672
2016/03/13 19:25:17 DEBUG: Creating new server: 10.4.129.11
2016/03/13 19:25:17 DEBUG: Checking if server 10.4.129.11 is slave
2016/03/13 19:25:17 DEBUG: Server 10.4.129.11 is not a slave. Setting aside
2016/03/13 19:25:17 DEBUG: Creating new server: 10.4.129.12
2016/03/13 19:25:17 DEBUG: Checking if server 10.4.129.12 is slave
2016/03/13 19:25:17 DEBUG: Server 10.4.129.12 is configured as a slave
2016/03/13 19:25:17 DEBUG: Server 10.4.129.11 was autodetected as a master
2016/03/13 19:25:17 DEBUG: Checking if server 10.4.129.12 is a slave of server 10.4.129.11

maxscale / # /usr/local/bin/replication-manager --user=replmgr:pass --rpluser=repl:pass --hosts=10.4.129.11,10.4.129.12 --switchover=keep --logfile=/var/log/mrm.log --version
MariaDB Replication Manager version 0.6.0-9450672
2016/03/13 19:25:32 ERROR: Could not autodetect a master!
maxscale / #
```

**Comment by jerrylin0** [comment]
Hi All ,

When I test the switchover function ,I also got the fail .
The error message as below :
2016-03-14 11:58:19 INFO : Slave mdb1:3306 [0] has been elected as a new master
 2016-03-14 11:58:19 DEBUG: Election rig: mdb1:3306 elected as preferred master
 2016-03-14 11:58:19 DEBUG: Checking eligibility of slave server mdb1:3306
 2016-03-14 11:58:19 DEBUG: Processing 2 candidates
 2016-03-14 11:58:19 INFO : Electing a new master
 2016-03-14 11:58:19 INFO : Checking long running updates on master
 2016-03-14 11:58:19 INFO : Flushing tables on mdb2:3306 (master)
 2016-03-14 11:58:19 INFO : Starting master switch
 2016-03-14 11:58:04 Monitor started in switchover modepanic: runtime error: invalid memory address or nil pointer dereference
                                 [signal 0xb code=0x1 addr=0x0 pc=0x40cb38]

                                                                           goroutine 1 [running]:
    panic(0x701e80, 0xc820010100)
                                        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
                                                                                   main.(*ServerMonitor).delete(0xc82008a500, 0x8f31e0)
                                                /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/monitor.go:259 +0x208
                                                 main.masterFailover(0xc82039be00)
                                                                                        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/failover.go:44 +0x9d1
                                                                                         main.main()
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/repmgr.go:309 +0x2984

And when the mrm do the failover steps ,it also fail to failover ,the error message as below :
2016/03/14 12:04:28 INFO : Server mdb2:3306 is dead.
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x701e80, 0xc82000e0c0)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.(*TermLog).Add(0x8f3200, 0xc82005a5c0, 0x33)
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/termlog.go:19 +0x3bb
main.logprint(0xc82012d400, 0x1, 0x1)
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/display.go:99 +0x560
main.masterFailover(0x7fff126fb701)
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/failover.go:12 +0x13d
main.main()
        /home/tanj/Dev/go/src/github.com/mariadb-corporation/replication-manager/repmgr.go:284 +0x2172

**Comment by tanji** [comment]
Hi @himbeere ! 
There was something which was put accidentally in a verbose check, and since I test all the builds in verbose mode, this one went through... :/

Please download the last version, it contains the fix. Sorry for this.

@jerrylin0 : can you open a different bug case? Thanks

**Comment by himbeere** [comment]
Hi @tanji 

I suppose you're in the process of uploading a new version? Just asking because latest version seems to be 0.60 from 4 days ago.

thanks and cheers
t.

**Comment by tanji** [comment]
Check it out here
https://github.com/mariadb-corporation/replication-manager/releases/tag/0.6.1
